import type { Skill } from "@/lib/skills/types";
import { narrativeSchema, dataSchema, valuationSchema } from "@/lib/skills/schemas";

// The 15-skill catalog (PRD §12). Firm-managed config, not user-authored.
// Non-CIM prompt instructions are functional starting points; refine with the firm (PRD §23 Q1).

export const CATALOG: Skill[] = [
  // ---------- Track A — Sell-side (9) ----------
  {
    key: "sell.client_profile",
    track: "sell",
    step: 1,
    name: "Client profile",
    description: "Research brief on the target company for pre-engagement prep and prospect meetings",
    phase: "Pre-engagement",
    estMinutes: 8,
    format: "docx",
    archetype: "narrative",
    chainsFrom: [],
    inputs: [
      { name: "companyName", label: "Company name", type: "text", autoFrom: "project.companyName", required: true },
      { name: "website", label: "Website", type: "text", autoFrom: "project.website" },
      { name: "researchFocus", label: "Research focus notes", type: "textarea" },
    ],
    instruction:
      "Produce a concise company research brief: overview, products/services, market position, ownership, and notable risks/opportunities relevant to a potential sell-side engagement.",
    outputSchema: narrativeSchema,
  },
  {
    key: "sell.valuation",
    track: "sell",
    step: 2,
    name: "Business valuation",
    description: "Multi-method valuation model with SBA financeability test and comparable transactions",
    phase: "Pre-engagement",
    estMinutes: 12,
    format: "xlsx",
    archetype: "model",
    chainsFrom: ["sell.client_profile"],
    inputs: [
      { name: "revenueTtm", label: "Revenue (TTM)", type: "number" },
      { name: "ebitda", label: "EBITDA", type: "number" },
      { name: "ownerAddbacks", label: "Owner add-backs", type: "number" },
      { name: "multipleRange", label: "Industry multiple range", type: "text", placeholder: "e.g. 4.0x–6.0x" },
      { name: "comps", label: "Comparable transactions notes", type: "textarea" },
      { name: "sbaTest", label: "Run SBA financeability test", type: "toggle", defaultValue: "true" },
    ],
    instruction:
      "Supply valuation inputs and assumptions ONLY (do not compute final figures in prose). Provide EBITDA, add-backs, and a low/high multiple range; list key assumptions. The spreadsheet template computes the valuation range, DCF, and SBA financeability.",
    outputSchema: valuationSchema,
  },
  {
    key: "sell.market_assessment",
    track: "sell",
    step: 3,
    name: "Market assessment",
    description: "7-slide presentation showing the owner their market opportunity and valuation range",
    phase: "Prospect meeting",
    estMinutes: 10,
    format: "pptx",
    archetype: "narrative",
    chainsFrom: ["sell.valuation"],
    inputs: [
      { name: "audience", label: "Target audience", type: "text", defaultValue: "Business owner" },
      { name: "talkingPoints", label: "Key talking points", type: "textarea" },
    ],
    instruction:
      "Produce a ~7-section deck (one section per slide): title, market overview, demand drivers, comparable activity, valuation range, process overview, and next steps. Keep each slide tight.",
    outputSchema: narrativeSchema,
  },
  {
    key: "sell.engagement",
    track: "sell",
    step: 4,
    name: "Engagement agreement",
    description: "Sell-side advisory engagement letter with fee schedule, exclusivity, and term provisions",
    phase: "Engagement launch",
    estMinutes: 8,
    format: "docx",
    archetype: "narrative",
    chainsFrom: ["sell.client_profile"],
    inputs: [
      { name: "successFee", label: "Success fee %", type: "text", autoFrom: "firm.defaults.success_fee" },
      { name: "retainer", label: "Retainer (monthly)", type: "text", autoFrom: "firm.defaults.retainer" },
      { name: "exclusivity", label: "Exclusivity period", type: "text", autoFrom: "firm.defaults.exclusivity" },
      { name: "scope", label: "Scope notes", type: "textarea" },
    ],
    instruction:
      "Draft a sell-side advisory engagement letter with sections for scope of services, fee schedule (success fee + retainer), exclusivity, term, and standard terms. Use the firm's defaults where provided.",
    outputSchema: narrativeSchema,
  },
  {
    key: "sell.data_room_checklist",
    track: "sell",
    step: 5,
    name: "Data room checklist",
    description: "Customized document request list tailored to the client's business type and deal stage",
    phase: "Engagement launch",
    estMinutes: 6,
    format: "xlsx",
    archetype: "data",
    chainsFrom: ["sell.client_profile"],
    inputs: [
      { name: "businessType", label: "Business type", type: "text", autoFrom: "project.industry" },
      { name: "dealStage", label: "Deal stage", type: "text" },
    ],
    instruction:
      "Produce a categorized due-diligence document request list (columns: Category, Document, Notes, Priority). Tailor categories to the business type.",
    outputSchema: dataSchema,
  },
  {
    key: "sell.cim",
    track: "sell",
    step: 6,
    name: "CIM generator",
    description: "Full confidential information memorandum for buyer marketing and due diligence",
    phase: "Marketing prep",
    estMinutes: 15,
    format: "docx",
    archetype: "narrative",
    badges: ["updated"],
    chainsFrom: ["sell.valuation", "sell.client_profile"],
    inputs: [
      { name: "yearFounded", label: "Year founded", type: "text" },
      { name: "employees", label: "Number of employees", type: "text" },
      { name: "revenueTtm", label: "Revenue (TTM)", type: "text" },
      { name: "valueDrivers", label: "Key value drivers", type: "textarea" },
      { name: "reasonForSale", label: "Reason for sale", type: "text" },
    ],
    instruction:
      "Produce a Confidential Information Memorandum. Required sections: Executive Summary; Investment Highlights (as bullet points); Business Overview; Products & Services; Market & Competition; Financial Summary; Growth Opportunities; Transaction Overview. Use the title 'CONFIDENTIAL INFORMATION MEMORANDUM', subtitle = company legal name, preparedBy = the firm name, and a current date. Ground all figures in the provided context; do not invent financials.",
    outputSchema: narrativeSchema,
  },
  {
    key: "sell.teaser",
    track: "sell",
    step: 7,
    name: "Teaser generator",
    description: "Anonymous one-page blind profile for pre-NDA buyer outreach",
    phase: "Pre-NDA outreach",
    estMinutes: 6,
    format: "docx",
    archetype: "narrative",
    chainsFrom: ["sell.cim"],
    inputs: [
      { name: "anonymization", label: "Anonymization level", type: "select", options: ["Standard", "High"], defaultValue: "Standard" },
    ],
    instruction:
      "Produce a one-page anonymized teaser/blind profile from the CIM: a generic business description (no identifying details), investment highlights, financial summary ranges, and a contact line. Never reveal the company name or location.",
    outputSchema: narrativeSchema,
  },
  {
    key: "sell.buyer_research",
    track: "sell",
    step: 8,
    name: "Buyer research",
    description: "Buyer universe with strategic and financial buyer contacts, rationale, and outreach notes",
    phase: "Concurrent with CIM",
    estMinutes: 14,
    format: "xlsx",
    archetype: "data",
    chainsFrom: ["sell.client_profile", "sell.valuation"],
    inputs: [
      { name: "buyerTypes", label: "Buyer types", type: "select", options: ["Strategic + Financial", "Strategic", "Financial"], defaultValue: "Strategic + Financial" },
      { name: "geography", label: "Geography", type: "text" },
      { name: "count", label: "Target count", type: "number", defaultValue: "25" },
    ],
    instruction:
      "Produce a buyer universe table (columns: Buyer, Type, Rationale, Contact, Outreach notes). Include both strategic and financial buyers where requested.",
    outputSchema: dataSchema,
  },
  {
    key: "sell.loi",
    track: "sell",
    step: 9,
    name: "LOI generator",
    description: "Letter of intent draft for asset or stock purchase with key deal terms",
    phase: "Offer stage",
    estMinutes: 8,
    format: "docx",
    archetype: "narrative",
    chainsFrom: ["sell.valuation"],
    inputs: [
      { name: "purchasePrice", label: "Purchase price", type: "text" },
      { name: "structure", label: "Structure", type: "select", options: ["Asset sale", "Stock sale"], defaultValue: "Asset sale" },
      { name: "keyTerms", label: "Key terms / contingencies", type: "textarea" },
    ],
    instruction:
      "Draft a letter of intent (seller perspective) with sections for purchase price, structure, key terms, contingencies, exclusivity, and a non-binding clause.",
    outputSchema: narrativeSchema,
  },

  // ---------- Track B — Buy-side (6) ----------
  {
    key: "buy.client_profile",
    track: "buy",
    step: 1,
    name: "Client profile",
    description: "Buyer company research brief for pre-engagement prep and mandate definition",
    phase: "Engagement launch",
    estMinutes: 8,
    format: "docx",
    archetype: "narrative",
    chainsFrom: [],
    inputs: [
      { name: "companyName", label: "Buyer company", type: "text", autoFrom: "project.companyName", required: true },
      { name: "mandate", label: "Mandate notes", type: "textarea" },
    ],
    instruction:
      "Produce a buyer research brief: company overview, acquisition rationale, capacity, and mandate summary.",
    outputSchema: narrativeSchema,
  },
  {
    key: "buy.proposal",
    track: "buy",
    step: 2,
    name: "Buy-side proposal",
    description: "Advisory proposal presented to a buy-side client before engagement",
    phase: "Pre-engagement",
    estMinutes: 8,
    format: "docx",
    archetype: "narrative",
    badges: ["new"],
    chainsFrom: ["buy.client_profile"],
    inputs: [
      { name: "process", label: "Process overview", type: "textarea" },
      { name: "fees", label: "Fee structure", type: "text" },
      { name: "timeline", label: "Timeline", type: "text" },
    ],
    instruction:
      "Draft a buy-side advisory proposal: process overview, scope, fee structure, timeline, and why-the-firm.",
    outputSchema: narrativeSchema,
  },
  {
    key: "buy.engagement",
    track: "buy",
    step: 3,
    name: "Buy-side engagement agreement",
    description: "Engagement letter for buy-side advisory mandate with search criteria and retainer terms",
    phase: "Engagement launch",
    estMinutes: 8,
    format: "docx",
    archetype: "narrative",
    badges: ["new"],
    chainsFrom: ["buy.proposal"],
    inputs: [
      { name: "searchCriteria", label: "Search criteria", type: "textarea" },
      { name: "retainer", label: "Retainer terms", type: "text", autoFrom: "firm.defaults.retainer" },
      { name: "successFee", label: "Success fee", type: "text", autoFrom: "firm.defaults.success_fee" },
    ],
    instruction:
      "Draft a buy-side engagement letter: search criteria, scope, retainer + success fee, exclusivity, and term.",
    outputSchema: narrativeSchema,
  },
  {
    key: "buy.target_research",
    track: "buy",
    step: 4,
    name: "Acquisition target research",
    description: "Target company list matching buyer acquisition criteria with rationale and contact data",
    phase: "Search phase",
    estMinutes: 14,
    format: "xlsx",
    archetype: "data",
    chainsFrom: ["buy.client_profile"],
    inputs: [
      { name: "criteria", label: "Acquisition criteria (industry, size, geo)", type: "textarea" },
      { name: "count", label: "Target count", type: "number", defaultValue: "25" },
    ],
    instruction:
      "Produce a target company list (columns: Company, Fit rationale, Est. size, Location, Contact). Match the buyer's acquisition criteria.",
    outputSchema: dataSchema,
  },
  {
    key: "buy.target_profile",
    track: "buy",
    step: 5,
    name: "Target profile",
    description: "Deep-dive research profile on an individual acquisition target for outreach and screening",
    phase: "Outreach / screening",
    estMinutes: 10,
    format: "docx",
    archetype: "narrative",
    chainsFrom: ["buy.target_research"],
    inputs: [
      { name: "target", label: "Selected target", type: "text", required: true },
      { name: "screeningFocus", label: "Screening focus", type: "textarea" },
    ],
    instruction:
      "Produce a deep-dive profile on the selected target: overview, products, market position, fit assessment, and screening notes.",
    outputSchema: narrativeSchema,
  },
  {
    key: "buy.loi",
    track: "buy",
    step: 6,
    name: "LOI generator",
    description: "Letter of intent draft for asset or stock purchase from the buyer's perspective",
    phase: "Offer stage",
    estMinutes: 8,
    format: "docx",
    archetype: "narrative",
    chainsFrom: ["buy.target_profile"],
    inputs: [
      { name: "offerPrice", label: "Offer price", type: "text" },
      { name: "structure", label: "Structure", type: "select", options: ["Asset purchase", "Stock purchase"], defaultValue: "Asset purchase" },
      { name: "terms", label: "Terms", type: "textarea" },
    ],
    instruction:
      "Draft a letter of intent (buyer perspective): offer price, structure, key terms, due-diligence and exclusivity, and a non-binding clause.",
    outputSchema: narrativeSchema,
  },
];
